import { FIELDS } from './fields.js'
import { SuperJoyCommandError } from './error.js'

const names = {
	hdmiout: 'HDMI Output Control',
	custom: 'Trigger Custom Button',
	camselect: 'Select Group and Camera',
	directpresets: 'Select Group, Camera, and Preset',
	presets: 'Select Preset on Current Camera',
}

/**
 * Class representing PTZ SuperJoy actions.
 * @class
 * @param {Object} superJoyInstance - The instance of the SuperJoy controller.
 *
 * This is implemented as a class so that the SuperJoy instance can be stored
 * as a member variable for use in callbacks.
 */
export class PTZSuperJoyActions {
	/**
	 * @property {PTZSuperJoyInstance} superJoyInstance - The instance of the SuperJoy controller.
	 */
	superJoyInstance = null

	constructor(superJoyInstance) {
		this.superJoyInstance = superJoyInstance
		this.initActions()
	}

	/**
	 * Callback function for handling action responses.
	 * @param {*} json - The json representation of the http response
	 * @param {*} data - callback data given by the caller with the current url added
	 */
	actionCallback = (json, data) => {
		if (json.result !== '0') {
			throw new SuperJoyCommandError(`Result is ${json.result}, expect zero`, {
				url: data.url,
				caller: this.superJoyInstance,
			})
		}
		this.superJoyInstance.updateState()
	}

	/**
	 * Takes a string value generated by potentially parsing variables in a field and validate
	 * that it is an integer in the given range and returns the stringa
	 * @param {string} name Name of the Action used to generate good error messages
	 * @param {string} valueTxt Incoming text value to be validated
	 * @param {number} min Minimum valid value
	 * @param {number} max Maximum valid value
	 * @param {string} fieldName Name of the field being validated for good error messages
	 * @returns number
	 */
	validateNumberInRange(name, valueTxt, min, max, fieldName) {
		let num = Number(valueTxt)
		if (!Number.isInteger(num)) {
			throw new SuperJoyCommandError(`${names[name]}: ${fieldName} must be an integer, got ${valueTxt}`)
		}
		if (num < min || num > max) {
			throw new SuperJoyCommandError(
				`${names[name]}: ${fieldName} must be a number between ${min} and ${max}, got ${num}`,
			)
		}
		return num.toString()
	}

	/**
	 * Validate that both a group and camera ID are valid, taking into account that group 5
	 * allows camera IDs up to 255 and the reset are just 1-6.
	 * @param {string} name name of the Action used to generate good error messages
	 * @param {string} groupTxt incoming group text value
	 * @param {string} camTxt
	 * @returns {group: string, camid: string}
	 */
	validateGroupAndCamera(name, groupTxt, camTxt) {
		let group = this.validateNumberInRange(name, groupTxt, 1, 5, FIELDS.Group.label)
		let camMax = 6
		if (group == 5) {
			camMax = 255
		}
		let camid = this.validateNumberInRange(name, camTxt, 1, camMax, FIELDS.Camera.label)
		return { group: group, camid: camid }
	}

	/**
	 * Initialize action definitions for the SuperJoy controller.
	 */
	initActions() {
		let actions = {
			hdmiout: {
				name: names['hdmiout'],
				options: [FIELDS.HDMIControl],
				callback: async (action) => {
					let argMap = new Map([['action', action.options.hdmicontrol]])
					this.superJoyInstance.sendCommand('hdmiout', argMap, {
						function: this.actionCallback,
						data: null,
					})
				},
			},
			custom: {
				name: names['custom'],
				options: [FIELDS.CustomButton],
				callback: async (action) => {
					buttonTxt = await this.superJoyInstance.parseVariablesInString(action.options.buttonid)
					buttonId = this.validateNumberInRange('custom', buttonTxt, 1, 5, FIELDS.CustomButton.label)
					let argMap = new Map([
						['action', 'trigger'],
						['buttonid', buttonId],
					])
					this.superJoyInstance.sendCommand('custom', argMap, {
						function: this.actionCallback,
						data: null,
					})
				},
			},
			camselect: {
				name: names['camselect'],
				options: [FIELDS.Group, FIELDS.Camera],
				callback: async (action) => {
					let groupTxt = await this.superJoyInstance.parseVariablesInString(action.options.group)
					let camidTxt = await this.superJoyInstance.parseVariablesInString(action.options.id)
					let groupAndCam = this.validateGroupAndCamera('camselect', groupTxt, camidTxt)
					let argMap = new Map([
						['group', groupAndCam.group],
						['camid', groupAndCam.camid],
					])
					this.superJoyInstance.sendCommand('camselect', argMap, {
						function: this.actionCallback,
						data: null,
					})
				},
			},
			directpresets: {
				name: names['directpresets'],
				options: [FIELDS.Group, FIELDS.Camera, FIELDS.Preset, FIELDS.Speed],
				callback: async (action) => {
					let groupTxt = await this.superJoyInstance.parseVariablesInString(action.options.group)
					let camidTxt = await this.superJoyInstance.parseVariablesInString(action.options.id)
					let groupAndCam = this.validateGroupAndCamera('directpresets', groupTxt, camidTxt)

					let presetTxt = await this.superJoyInstance.parseVariablesInString(action.options.preset)
					let presetSpeedTxt = await this.superJoyInstance.parseVariablesInString(action.options.speed)
					let preset = this.validateNumberInRange('directpresets', presetTxt, 1, 255, FIELDS.Preset.label)
					let presetSpeed = this.validateNumberInRange('directpresets', presetSpeedTxt, 1, 24, FIELDS.Speed.label)
					let argMap = new Map([
						['action', 'recall'],
						['group', groupAndCam.group],
						['camid', groupAndCam.camid],
						['preset', preset],
						['presetspeed', presetSpeed],
					])
					this.superJoyInstance.sendCommand('directpresets', argMap, {
						function: this.actionCallback,
						data: null,
					})
				},
			},
			presets: {
				name: names['presets'],
				options: [FIELDS.Preset, FIELDS.Speed],
				callback: async (action) => {
					let presetTxt = await this.superJoyInstance.parseVariablesInString(action.options.preset)
					let presetSpeedTxt = await this.superJoyInstance.parseVariablesInString(action.options.speed)
					let preset = this.validateNumberInRange('presets', presetTxt, 1, 255, FIELDS.Preset.label)
					let presetSpeed = this.validateNumberInRange('presets', presetSpeedTxt, 1, 24, FIELDS.Speed.label)

					let argMap = new Map([
						['action', 'recall'],
						['preset', preset],
						['presetspeed', presetSpeed],
					])
					this.superJoyInstance.sendCommand('presets', argMap, {
						function: this.actionCallback,
						data: null,
					})
				},
			},
		}
		this.superJoyInstance.setActionDefinitions(actions)
	}
}
